### ISSUE TITLE
Using the Image Plugin

### ISSUE THREAD

**Issue by daslicht** [bergie/hallo#195]
Hello,
is there somewhere an example how to use the Image Plugin and how to upload Images ?
please ?

~Marc

**Comment by clov3rly** [comment]
@daslicht did you get this working? I haven't seen any docs or examples for how to actually upload and insert images, though it doesn't throw any errors in the version I'm using.

**Comment by daslicht** [comment]
@clov3rly I can't remember, have you tried the solution grobmeier proposed?
