### ISSUE TITLE
Hallo doesn't display toolbar icons when using font-awesome 4.0.3

### ISSUE THREAD

**Issue by techmsi** [bergie/hallo#212]
Hallo *doesn't display*  toolbar icons when using font-awesome 4.0.3 because the classes have changed:
http://fontawesome.io/icon/italic/

**Font Awesome 4.0.3**
```
<i class="fa fa-italic"></i>
```

**Font Awesome 3.2.1**
```
<i class="icon-italic"></i>
```

**What files/lines would need to be changed in order to work with the newest font-awesome code?**

**Comment by bergie** [comment]
Fixed by #213
