### ISSUE TITLE
showAlways do not work

### ISSUE THREAD

**Issue by difanz** [bergie/hallo#85]
Did a grep and did not find anything related with "showAlways" which is included in http://hallojs.org/demo/annotate/

I think it is something important and should be there.

**Comment by djvs** [comment]
Hmm...I have:

              toolbar: 'halloToolbarFixed',
              showAlways: true,

and it's still not showing it unless the hallo div is focused.  Am I using the wrong option?

**Comment by djvs** [comment]
Hmm...guess the only solution is CSS?

     .hallotoolbar{ display:block !important; }
